### ISSUE TITLE
Option to use base stats

### ISSUE THREAD

**Issue by KyokoDolls** [goldenguy00/LemurFusion#11]
I very much enjoy the mod. It lets me play without having to worry about environmental damage, and it lets me have the scoreboard up to view items, as well as being able to have advanced ai for my little friends to live longer. Having said that, the base stats for the lemuians feel a bit strong to play with. I looked for an option to just plat with base stats, but i couldn't find one.  If thee indeed isnt one, could an option be put in place to let me play with this mod using the vanilla base stat totals for the lemurians? I appreciate you taking the time to look at this and your work on this mod.

**Comment by goldenguy00** [comment]
the vanilla stats can be used if you set this in your config
![{67433032-A3F5-445D-8C6F-A727687E4243}](https://github.com/user-attachments/assets/5b46a028-66af-4cc2-b407-53fea09e7bef)

**Comment by KyokoDolls** [comment]
I've tried that. It does work for most stats, but weirdly their attack speed is still much higher with this mod on than without. Ive run the game with this mode activated and deactivated, summoning a lemurian on the first stage as soon as possible, and the lemuians i summon right at the start of the game definitely attack faster with the mod on than with it off.

**Comment by goldenguy00** [comment]
Will be fixed next patch, found the issue. Thanks
