### ISSUE TITLE
Mod Is Missing Dependencies?

### ISSUE THREAD

**Issue by Sorukun21** [goldenguy00/LemurFusion#2]
Is it me or is the mod currently missing its dependencies? I tried launching my game with the mod installed, and the console forced closed itself after a few seconds.

**Comment by goldenguy00** [comment]
id have to see a log to help...

**Comment by goldenguy00** [comment]
it is highly recommended to use r2modman if you arent

**Comment by goldenguy00** [comment]
updated manifest in v1.0.6, that should fix it. lmk if youre still having problems
