### ISSUE TITLE
scoreboard broken in multiplayer

### ISSUE THREAD

**Issue by Astron0** [goldenguy00/LemurFusion#5]
In multiplayer, when I play with my friend who is running the same mod with the exact same settings (I gave her my profile from r2modman) the lemurian scoreboard for her is broken. When she presses tab it shows up with the icon of whichever character I'm playing instead of a lemurian (e.g. if I'm playing commando, what should be the icon of a lemurian that she's spawned in will show up as commando) and instead of the name being "lemurian", it shows up as a hyphen. No items she gives them shows up in the box either, it's glitched. It works fine for me though. I have yet to test it out when she is the host instead of me.

**Comment by Astron0** [comment]
Edit: just tested it, the scoreboard only functions properly for the host. Anyone who joins the host gets a broken scoreboard as described above.

**Comment by goldenguy00** [comment]
okay ill get a fix out for that, thanks. i haven't tested multiplayer functionality a ton, so let me know if you run into any other issues

**Comment by Astron0** [comment]
Thanks alot, unrelated but I've really been enjoying this mod, got everything I'd hoped for that was missing from the vanilla devotion, appreciate your efforts, have a nice day

**Comment by goldenguy00** [comment]
fixed i think
