### ISSUE TITLE
Elder Lemurian allies constantly spam fireball noise.

### ISSUE THREAD

**Issue by Aaron00000** [goldenguy00/LemurFusion#8]
It sounds like the Elder Lemurian is trying to activate fireballs about twenty times a second any time it is trying to attack an enemy. I've tried meddling with various AI settings to see if any of them were the culprit, with no luck.

[LogOutput.log](https://github.com/user-attachments/files/17942575/LogOutput.log)

**Comment by goldenguy00** [comment]
fixed
